kind: pipeline

steps:
- name: deploy
  image: appleboy/drone-ssh:1.5.5
  pull: always
  settings:
    host: 148.72.144.75
    port: 22
    command_timeout: 10m
    username: root
    password: 
      from_secret: live-password
    script: 
      - cd /var/www/turbo-bpo-live/
      - git checkout staging
      - git pull
      - systemctl stop turbo-fe-staging.service
      - systemctl start turbo-fe-staging.service
  when:
    branch:
    - staging
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: dev
    icon_url: https://unsplash.it/256/256/?random   

  
  
