export default [
  { value: 'custom', label: 'CUSTOM(iForm Only)' },
  { value: 'ALTISOURCE-MKT', label: 'ALTISOURCE-MKT' },
  { value: 'ALTISOURCE-VP', label: 'ALTISOURCE-VP' },
  { value: 'AVM', label: 'AVM' },
  { value: 'BPO.COM', label: 'BPO.COM' },
  { value: 'BPOFULFILLMENT', label: 'BPOFULFILLMENT' },
  { value: 'CLEAR CAPITAL', label: 'CLEAR CAPITAL' },
  { value: 'COMPUTERSHARE', label: 'COMPUTERSHARE' },
  { value: 'CONSOLIDATED', label: 'CONSOLIDATED' },
  { value: 'CORELOGIC VS', label: 'CORELOGIC VS' },
  { value: 'EMORTGAGE LOGIC', label: 'EMORTGAGE LOGIC' },
  { value: 'EQPOINTE', label: 'EQPOINTE' },
  { value: 'EQUATOR', label: 'EQUATOR' },
  { value: 'FASINC', label: 'FASINC' },
  { value: 'FIRSTAM', label: 'FIRSTAM' },
  { value: 'GOODMAN DEAN', label: 'GOODMAN DEAN' },
  { value: 'IMORTGAGE', label: 'IMORTGAGE' },
  { value: 'INFINITY', label: 'INFINITY' },
  { value: 'INSIDE VALUATION', label: 'INSIDE VALUATION' },
  { value: 'INSPORT', label: 'INSPORT' },
];
