export default {
  Distance: 'distance',
  'MLS #': 'mlsNumber',
  Status: 'st',
  'Num of Stories': 'numberOfStories',
  'Styles of Residence': 'styleOfResidence',
  'Street Name': 'address',
  'Town/City': 'city',
  Zip: 'zipCode',
  'Original List Date': 'listDate',
  'Days on Market': 'dom',
  'Original List Price': 'originalListPrice',
  'Sale Price': 'salePrice',
  'Sale Date': 'closeDate',
  'Num of Heating Units': 'numberOfHeatingUnits',
  'Lot Size': 'numuberOfAcres',
  'Square Footage': 'squareFootTotal',
  'Year Built': 'yearBuild',
  'Total Rooms': 'totalRooms',
  'Beds Total': 'bedsTotal',
  Bathrooms: 'batFull',
  'Half Baths': 'bathsHalf',
  'Num of Garage Spaces': 'numberOfGrageSpaces',
  'Garage Description': 'garageDescription',
  'Basement Description': 'basementDescription',
  Waterfront: 'isWaterFrontYn',
  'Sale Type': 'typeOFSale',
  'Terms of Sale': 'termOfSale',
  Subdivision: 'subdivisionCommComplex',
  'Additional Exterior Features': 'additionalExteriorFeatures',
  'MLS Comments': 'publicRemarks',
};
