export const websites =  {
'custom': '',
'ALTISOURCE-MKT': 'https://marketplace.realtrans.com/vp-ui/',
'ALTISOURCE-VP': 'https://valuations.realtrans.com/realtrans-vp/auth/sec/login',
'AVM': 'http://www.assetval.com',
'BPO.COM': 'http://www.brokerpriceopinion.com',
'BPOFULFILLMENT': 'https://www.bpofulfillment.com/Login.aspx',
'CLEAR CAPITAL': 'http://www.clearcapital.com',
'COMPUTERSHARE': 'https://vendors-cms.clearvalueconsulting.com/Account/Login',
'CONSOLIDATED': 'https://ca.quandis.net/Mortgage/Valuation.ashx/Home',
'CORELOGIC VS': 'https://www.vss20.com',
'EMORTGAGE LOGIC': 'https://www.emortgagelogic.com/login.html',
'EQPOINTE': 'https://ep.quandis.com/Security/Login.aspx',
'EQUATOR': 'http://www.equator.com',
'FASINC': 'http://www.fasinc.com/',
'FIRSTAM': 'https://www.amp.firstam.com/Resources/Home.aspx',
'GOODMAN DEAN': 'http://portal.goodmandean.com/login.aspx',
'IMORTGAGE': 'https://www.propertysmart.us/IMS_Vendor_Login.aspx',
'INFINITY': 'http://www.infinityvaluation.com/',
'INSIDE VALUATION': 'http://www.insidevaluation.com/',
'INSPORT': 'http://www.inspectionport.com',
'ISGN ': 'http://orders.isgn.com/loginf.html',
'LRES': 'http://www.lres.com/',
'MCS CORELOGIC': 'https://sn.mcsvaluations.com/Sourcenet3/Common/Login.aspx?ReturnUrl=%2fSourcenet3%2fCommon%2fLogin.aspx%2frl',
'NVS': 'https://www2.nationsvs.com/bpo/Account/LogOn',
'OLD REPUBLIC': 'https://vendor.orssvaluations.com/Account/Login?ReturnUrl=%2f',
'OTHER': 'https://vendor.orssvaluations.com/Account/Login?ReturnUrl=%2f',
'PCVM': 'http://dashboard.pcvmurcor.com/Login.aspx',
'POWERLINK': 'http://web.powerlinkss.com/vendor/ven_hold.asp',
'PROTECK': 'http://www.protk.com',
'REALTY PILOT': 'https://www.realtypilot.com',
'RES.NET': 'http://www.res.net',
'RRREVIEW': 'http://www.rrreview.com/',
'SAM': 'https://sam.quandis.net/Security/Login.ashx?ReturnUrl=%2f',
'SERVICELINK': 'https://valuations.svclnk.com/SpaConsumerPortal/index.html',
'SINGLE SOURCE': 'http://www.singlesourceproperty.com',
'Solidifi': 'www.solidifibpo.com',
'SOLUTIONSTAR': 'https://www.bpofulfillment.com/Login.aspx',
'STEWART': 'https://slsvendors.stewart.com/Account/Login',
'SUMMIT VALUATIONS': 'https://www.disposolutions.com/clientlogins/summit/default.aspx',
'SWBC': 'https://swbcls-vendors.clearvalueconsulting.com/Account/Login',
'TRAXREALTY': 'http://www.realtracs.net',
'TROPHY HOMES REALTY': 'https://www.realty.com/',
'USRES': 'http://www.usres.com',
'VALUATION PARTNERS': 'http://www.valuationpartners.com/vendors/',
'VALVISION': 'https://www.valuationvision.com/mobile/login_mobile.php',
'XOME': 'https://vendor.xomevaluations.com/'
}

